allprojects {
    repositories {
        google()
        mavenCentral()
    }
    
    // Fix motion_sensors plugin namespace issue
    project.plugins.withId('com.android.library') {
        if (project.name == 'motion_sensors') {
            project.android {
                namespace 'finaldev.motion_sensors'
            }
        }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
