org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# Force motion_sensors to use compatible versions
motion_sensors.kotlin_version=1.8.22
motion_sensors.compileSdkVersion=35
motion_sensors.namespace=finaldev.motion_sensors